apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  # image tags are relative; to specify an image repo (e.g. GCR), you
  # must provide a "default repo" using one of the methods described 
  # here:
  # https://skaffold.dev/docs/concepts/#image-repository-handling
  - image: data-api
    context: services/data-api
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./k8s-manifests/**.yaml