apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: bitnami/mongodb:4.2.3
        ports:
        - containerPort: 27017
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 27017
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 27017
        volumeMounts:
        - mountPath: /bitnami/mongodb
          name: mongodb-data
        env:
          - name: MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: MONGODB_USERNAME
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: MONGODB_PASSWORD
          - name: MONGODB_DATABASE
            value: weather
        resources:
          limits:
            memory: 256Mi
            cpu: 125m
          requests:
            memory: 200Mi
            cpu: 70m
      volumes:
      - name: mongodb-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  MONGODB_USERNAME: dXNlcg==
  MONGODB_PASSWORD: bW9uZ29wYXNz
