apiVersion: v1
kind: Service
metadata:
  name: service-tracker-ui
spec:
  type: NodePort
  selector:
    app: service-tracker-ui
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 32000